creation_rules:
  - path_regex: \.sops\.yaml$
    age: age13tcz5qhkdc0vqpxk7j8kee7eh23l6gcfc8pr5nycvcjpd557a3csu2lkxt
  - path_regex: talosconfig(\.sops)?$
    age: age13tcz5qhkdc0vqpxk7j8kee7eh23l6gcfc8pr5nycvcjpd557a3csu2lkxt
  - path_regex: backup/.+(\.sops)?\.yaml$
    age: age13tcz5qhkdc0vqpxk7j8kee7eh23l6gcfc8pr5nycvcjpd557a3csu2lkxt
