apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # Temporarily disabled to recover from failed HelmRelease state.
  # - ./n8n/
  - ./nextcloud/
  - ./pihole/
  - ./vibe/
  - ./excalidraw/
  - ./renovate/
