---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: renovate-github-token
  namespace: renovate
spec:
  encryptedData:
    token: AgCbqnUGMaTYetULTiCdKhTDBE6FGnwcy2XTyYlMplvZ2UtcfX1SiuL1MMNZ7RWl9ZLOhTndzrsAldUtQOpNXU6ASJ6Kz81wnS66H8iWt4q4sIB7zTO7fZN7JfVoVHGUjZapIMgHTOhKiL7Nxux9/Pb4P3SE5IIIocVH2RuP2nIngGxPQV0xUsANeJV6ADTlvpYxCQ3e0OgxyGeAW9Qe59Ue7ZT7V2//qWavOtsBsnADG0kaUcQb0DQvP2V/fG4QpVzj/yUn3SgwLmDVeeZ9ADPxpKJ9SJwQi/quRxcmhD4ze2Ckfws0zrMUGyQLmb5QC26rB/AHYCzViBv2Dq6nCk14U8SYIz3gv85ztabFNnpLR98zFJVFEZ1AzctbhOAhXvkvYOGUcSMWBy1m5Zzxva8rWpvmN1mYJ3/4DkVabs8Ql5pbf1d7c9UIJEYHiGMSizbhNI+tnVYr57cNCL2ygePhehfiiy0baex5E2nwYBx7Et8AHoXajfyxqWqLDmTUoa0n2vQw8mNmmDN+yNQjqhVMTZZrxcPtMNviS1FmGp4Ild9U5tj4wvM9bHSSPTmiT9mDyt7DNDCXiWvuoaS0KJQoPeLhbyAjKxRpDmdYdZHLdwSt8mYCVRx0QZoNPMCBIzvzTJi8+/7PHc9+n4aT98BKj92I0mtEdPNJFYTWnocEYYn15OEIgkF3e/1BivH1Kw0Vi1uNm5kVqOpp6VMGX4I2ovIMsEA1Q4Bhu2K6voiXiCbJIHl2TCJ7
  template:
    metadata:
      name: renovate-github-token
      namespace: renovate
    type: Opaque
