---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: renovate-github-token
  namespace: renovate
spec:
  encryptedData:
    token: AgBU3eBHdZLx+vEi+601PmmI1S8XE6gq8hCX0Ud72i5F/PlZT6Qx8yo6aekdIAaKv81K7AQSfxRj0xYKSQMpT0OhE5e4ZSzBmwJE86wnjY27nQzhBdg37//gnLL9TcXbYiUcgW2MtYyrB6Eup2fB//nrBX9U0VgQwwFoHCM98SK75ljKig/fpXcBUiEa9o5LAbO9c5GMb81RUMs76LfAjcH7QILd6ZRrLAAXloFhjzN6pv3OVvID1JVmZikIW7obIaraujsbZlsgUsjeZVznfRev3budL/VfWNc4x+/9nbwVBavT+uWrdfD8+zcu3Kgo0ryiLU72xgG/KKzjz+1vhghTFsireUFWEQ1L1n0+1/16ZEmw62vfHI9sIAkezqlcY22Dpiv1irFDwIGPld00WfyGisQ4Cgfb5ODdO5ZsuWrSJr0ndr/INbak41PQ290DnxPiUUp8nszdkmAZtxe/bgA1fkT196n67AFEHpbocJSX3CA+0T1GpHM/xMvF9zjZjZPO8c30I3qQ+lapritkWxzyAlRuZ4jF1HzLLuV5ZUwIvIuCnTIXemar5bjok0WA6P8y7DX+j17EDZMUiMflbsWugnO2SI/qWnZRw5+5xjZhDCSScxGyaiP94biYe14mF2BoGXj3kyVg8jfbodqE5wHGuILQzM2AByFcdrH15kxXDbqJgumPfjtKoMnzSBMFBxf4VM1ozw+A4oGAVPrTvPNQNAzmV3e0tuGq0DsHraBGheefcYqDNWSk
  template:
    metadata:
      name: renovate-github-token
      namespace: renovate
    type: Opaque
