---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: renovate-github-token
  namespace: renovate
spec:
  encryptedData:
    token: AgBDxja12LaZsr7CZl79mNNhC5UP6HcHJf9DwQYU/6OPP0Vh6EBor036QLyf5KsvNZMyQuNC0F1Ublvo0gkARcnkDtYkHCiESH3RB1uAdlEOXnOIBlF2x21DEo/I7IA3jYgzKDhFjhHip26Pq6Cz3MOw8aT0ZsuJ5D46LQW63s1tjXYSkn6wuhmD40eWjewEwSFC6DsjBV+PmvgQ3bw8eggOKNzZjFXTW9cTlq78zTy5Yv/kiWuI8PsRhyRXK1ZfjePo70V4HgbsoxG7uMxODj0jyzrUNTeBCSlZgDeJpteHTmTb+oZD5gwWLPKuV4U5rBqdnHxO/h1+KN7AZ8tu4407nJ+RJdGaDybwxUz+/p62Ncci4sV6UlfXsnRp69wfhDGoWh3kW4Uzh6Tzh8cGjMo8mfGli+leckdagvVx6juv6YcVPvTcabjJ75neoM26Wxj13rDoof4dk1lBVi7GDS7wnGazvucM/U9JmEx38NVmAWXFzCRViJCvBj8Vtw9XV3KB8KawZvNxFuvYEmQt/Cy5THAaH72UBTZhyxTE51h4fhk9RmWf12bEZL3f9mAf5awLuNFM5XgQfPu2/TyqFUMEjs8vW5XZysXV4ASrxLv5QjeXPhr/fDAbZnVP8Xc3uIEEC3jUkbQB6sgtjhrXuUNgWUcN0/Ph0N7dSfaKy9iupq8oYzcS+8ZL5XFOI57jYuWhOhmE4XSxC/Le0owecM1yUx6lm5/VKdO2ae3iAtJ5cPVi8FdvHspB
  template:
    metadata:
      name: renovate-github-token
      namespace: renovate
    type: Opaque
