apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./cert-manager/
  # Temporarily disabled to reduce pressure on the single-node cluster:
  # - ./cloudflare/
  - ./cnpg-operator/
  # - ./envoy-gateway/
  - ./longhorn/
  - ./metrics-server/
  # - ./pipelines-as-code/
  # - ./prometheus-stack/
  # - ./tekton/
  # - ./velero/
