---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: silverbullet-auth
  namespace: silverbullet
spec:
  encryptedData:
    SB_USER: AgAg5EOGEtkGXfyI0kZ4zOX5yS3g4h98IQTfeRIgpW5c+3K/jBdNluPnwZlu9iJZYlkGtNB/qJIep+W+Sx0X+5fLs6HLKzAucZou94xsiApyA55QHYMpEx4pjgNFUhFp272Bo+rDyJasuLOqrYwJxX5z0JO8wU4e8F0ptwXhq+eAVE6F3GRhFREx+S2AolG6oigTa22uTPaFpdSyqh9/1DW4UnCWk81O/9Hcb+ILJ+un3njWJ3h0k2IL42BoemIT8Rup9kwYP4c3/bTkoo35LpExQIjknsFWV4KCB6+PhYOlmrDGEke/5D7m5wnG2vi5MFdINUKDqNT9xfsLh0AAvGEjQ1VPMpSL2Nl/4rLDFfOoDELbEMzk8TonXma9cFHk8XknROTgdAYcUBUzHiVP1WS8sV6x/dp6L2u7jseRMF9HCjOKAqDMjHJPK3ELyveZ94IAnAkfmEwIrzvwULX4KWhgU70BSVd+tN48B5ZwrFkTE/j/69eVLaph+lzdkOwGZ1y4i2uO0BVlqrXV80NuutsYeutRF6j0fBokb7TIq6tyL/etcnEPP1sEBZnsQ/U0FbP/OWbm8eLoCofGUevHgIXnGdnqRThcDkixkMFewRR7pbhVXaskSmUyUZiG/8QS75fkm8TbHqMV8AY/k74yBW9oCJcoIZE0LN3YDWmPdhJorVOKq4KjxwwM4VqDv/QDQZTsf75wIeoRHIpXy0A1JcK14W6+rDaVJPLhYpYVuOOYUhgr4MPGhA==
  template:
    metadata:
      name: silverbullet-auth
      namespace: silverbullet
    type: Opaque
