[env]
KUBECONFIG = "{{config_root}}/kubeconfig"

[tools]
age = "1.3.1"
aws-cli = "2.34.29"
flux2 = "2.8.5"
github-cli = "2.89.0"
helm = "4.1.4"
kubectl = "v1.35.0"
kubeseal = "0.36.1"
sops = "3.12.1"
talhelper = "3.1.7"
talosctl = "1.12.6"
tekton = "0.43.1"
usage = "3.2.0"
velero = "1.18.0"
yq = "4.52.5"
