[env]
KUBECONFIG = "{{config_root}}/kubeconfig"

[tools]
age = "1.3.1"
aws-cli = "2.36.19"
flux2 = "2.9.4"
github-cli = "2.97.0"
helm = "4.2.3"
kubectl = "1.36.3"
kubeseal = "0.38.4"
sops = "3.13.3"
talhelper = "3.1.16"
talosctl = "1.13.8"
tekton = "0.46.0"
usage = "5.0.0"
velero = "1.18.2"
yq = "4.53.3"
