apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: silverbullet-space
  namespace: silverbullet
  labels:
    recurring-job.longhorn.io/source: enabled
    recurring-job.longhorn.io/longhorn-daily-volume-backup: enabled
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: longhorn
