apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: silverbullet
  namespace: silverbullet
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: silverbullet
  updatePolicy:
    updateMode: "Off"
