---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: harbor-valkey-credentials
  namespace: harbor
spec:
  encryptedData:
    REDIS_PASSWORD: AgCY5vfhkemuZMhC0S8wUD0hFntAhhRLkG8Gg9OZ5JYACgyOpySsMqYeMVOY08CP2q2EI62mgFPW89/OkclDDD3vsTted1TOjkZALg8fnAQzGYUxG5rs08xWtS02FTD3cVRTCBldMzoB0HKCpBZsX9RX9ijw2Ithj12Pa8fbeLt6UvE6iwYBoZrTgWN4IFWnp/Pxw1M2FuBumDnrj+CsTuMk1tug8Vb/3Ic7XbyAdNgE8shfIimRh4PUPCzD7T2bO2q4C6Huu88b1kUb4FoJHmHN3UJP0OA5K5+ay59FpryBt4kp+0GHL+cUR58QhqLoeuEayrGf7M76WpNKf5vg2gYiSJcn+d8prICDtJiDq1yMBN+NkwD7lx3HW9JXZL0Q0Dt/FUJP+q5c61UrFSd1mdqHc/TUG1fgpmhsSEBST5D7cVIOMUHY+O1HwiEtEstsiD/lxOMJh2lDKs01OpD8tLUR8vlgqzBKgDvUCyGmMQa0kZ0coMuL5HlEzAd6fMVm/xJMWU0EV+yi1iPv25jjqDpJK0rFDv9oae05WGyxxvkbeq7AvVEpFUyI8EmbV8DNMyXnKH2umoghbirJwOV3wJnUrkQdcfmzsVqfDV1agiuOfstuqinTcX2H7fXg0tTVgsnuELoqs1JhcOeFn2TPOKPSY0SkyLdOGAjR0NO9mWvI9s3X39Jh/6D30IbOMpd5xQxuJGhF5ZveO0CfsjGSVsz0+2HjxadKunki+7ZrSh3p4uSErlVXB21mvT965QjLyx06F6+hphPj+gIYgUnuNcSr
    redis-password: AgCc+gLfHwrLxfnU20RqO4pwY9+eNMzZDX+k3mr/6HLFfbnvues0j3iTYYpj01ab03K7L/eSt+O3j4OJaD9b0J5yKxw/K7Qd5JMoc5fE5loJkfXiUFv8mtintAdfqa8/NalirW3M+RaUbKFcLfYRhagZpwTSESbhcCATJpSdiDYpbnri/+00bCWoI6ueRL8vmtok0K56y1elx8VSgsHYqmGOutSXUuUck6cUkUGAxsspKte37tldvqAjNfAb3XFCUVgnVG4Tf1+adM8tk3X8GQuiCK6fH+7SW5buYj7u/JF6ghg4qoMcYSIN2Kz1mczM86WTnneop/ki8UsyJcEhHnMZ75XJGuxcHEh7zMkuc3CMCoYYkerRqOv2dLP2uuAA3fB1/HhaM7WbtFssV+IV9jX+ZxUhBiMdYMayFBIN8igG3tmnKKHVZGwf+RvyO9103KFmGspqWVZg5zdIVWcUlovlsaM9UZ4IeboIbV+mNb7h72nJHwUxr4tSB6rPBOveh0DPzjgO55tqAWRMOzFQd9/LR2ApLR3e92EBPTl1gi66M7f9wDDkbN+7+zgB5VKp/s6tDaOgstSa3UjUlLKikgkOP/QRaM1G0ges/0UAgUJw6Xt1+XSdjT/WXLFWreOClvAOBMbomihYH8aMEmV4ElvbRdv1mmoTCP2OqMCPc5orxiPYvB8g3BcsZ3cbSi8dNwUeYENfviRhvy9rsORLegkr3ubHgAofXcldJ0sPx0F67hPwtyxl83qpjW1Tp+wh4jnOTM/sv5QpQjSp33B0p58e
  template:
    metadata:
      name: harbor-valkey-credentials
      namespace: harbor
    type: Opaque
