---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: harbor-valkey-credentials
  namespace: harbor
spec:
  encryptedData:
    REDIS_PASSWORD: AgBVZl6ZyZlhdwHa7ktVZzyRpkhqvjOKHF2q26S+qXQyIZIdX9H5bvqDLVx6du8qCRMlGcIvdaw+znMupB+lhZ61PiLRtZAdbmmHieuXrAn2bodUeUHHh/p+CchvPv2GOr3Tk21FoDHn/4TRz+s6WEwEmtqOM5QFceJA8pVlzUO/I6Cc2OtwXBZrDjr9BY8vt9CWiM/v9uNLNNEd69rQrIPGAmqevw6bXU488N1IQRVPUOEhfdEg9hWBasqatF+DmxAba5U9aaSqmKOFs64unl/JWA289H2GDdCZWCG69SxGnZNghtlpJAtgkYLj4wzU8kle+fbo1i9XlGblZor8YvAA4MlfCoeZDunttDtGUZbWoTE5yxQYDUrVOhZVQGirGhCZxz5kVGigB33yyAlMrgpZUWH4li35Is9Hzx+hEMa8NUXc9NEs2XH+U0jDVuLhdsyZ0TQsoF+77UXrSGUlrFkcys5ITGg0TZpBnDF9/GiHg/hyMLX+O9n+uIHezaMs7+J1oA8KV5IFeHNz7VyF8G0GHD+I7E2E3DWeIOpkjRh6xWdJ/6gziVxv8mwJvv5Dmw6zHuOSOkB+uwNJKi0jvmmKsbUsKw/EwLBrTzOXGZ6rlyQn0K8f84HvEO1QxswUWuvgV3OrH+m7BYqYCJ2K/p2lz88/3BoKJUtsEjU3Bip8kQuaeIiBbrTxDJexRF550ELjM5R4/qqFV2U/85WnM2u65MBTsZjQf8MllEDRPMP5fi87O1dq3cyKVh/hFBJlwv68/QB+vAfnN375C7TUXcot
    redis-password: AgB1eCLbb2TGxJutPMOiW/daUNeUaDyekdTOoLPnuNDGTMW4sVMO5HEH9RB3w7RwtpjfddW+9/7e5TjVP+ie8iatrOqW+2nQ9dg2xKwFgwFFtOXORUyLOAKB2Vzt3ucbwng6ezOkOr8Ju+FSHZz5zO5TWyBA3xOob+E1olHrM52EyGJt9VRt5lAvRxp2vfbOrkiqHQAkDiwNpeY46DBBWgMN9b4vneUcILbMM21Mg5Yobe9ai3rroPG7/6RaoqLqyo6mxKzBbInWtNFHjJa4qy0jYA7pbR7srQx/vO20wNWAmvYr4SEauZJQLzy/MK9WiZ5RTIubryiBRTiSgczml1HBm61eiIDbs4R7he/yIPanL78HdNvQ146Rol7dLs9oIWRKbiISatGjxcO6WqYF0Wqx/TcS7mFiNgJETbjI13QiTy7+DHVudOq8cvryROEtT4OL6lcn+q/xttIr5NeQnGpE8TJnXzjrw+QzUArVIxuOONyPfxeeA7/YzTCZXMjim4J1M7pvmlgW1eWgIoXuUyXBIEsKJTYphk53JqGXYDkfp7Maa7JM1uYvVLE19CM8GD4FwB+ERuQc4gjdtoJOTXXSUowZSghpiKcR5W4V9KjmiHzy3sX2H0ewvN4n5c1z1omCBcBHgu1CN3Ot0dcUaPL/L32xjNawbkF/8yokPXk4gmxtwLO71sfd+JlM4r2CErVVsNgoaibUtKP/BzhZqIeQOzC1gg8B2pK+BvWJWgsIkR8/l87u7ELhNi5ZODiv8iGMPoEKLsPG8iuOSIiY+rgf
  template:
    metadata:
      name: harbor-valkey-credentials
      namespace: harbor
    type: Opaque
