---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: n8n-valkey-credentials
  namespace: n8n
spec:
  encryptedData:
    REDIS_PASSWORD: AgCB1dpx5YTAXRmF7mTkOplQkhqPXqVzPba1yt2aW4crGgTUg3i6SuX66wVZX3IBqkFPAs4adB1MPacA+fMph6DWgaW4uOCdf3E7l5Gvv6daa6elYvJ641+7TLs7owRy9LorT7baeKNEBwINyj4Nktro69nF4NZprJDjYw0BWFYnVxofaqxfUrvPWQmXPz9/p0fyY5M59rPztpueCWSCcLcMmV09tWryZgD0SXpeOE/eKtZW4ENAdHqETP9I22bWmy38wLQfh2gMrmZGNbb/Jh5aC0m4sSDM9VILgD8Y2B9GLFbqKUGpFGzG71zx0K45EbcMg7MUzFc0HaJy00czwzx+cQCRw1JzfWUBcNqRTtspf9r07/DR6YVAo+D9zz0Qx0FnPUwHHfnOJ+B0tNWkPAT4XfNYLMyZqdxINC5B0OHFoOqYZEUdrqWf6dp3xRPaNC20iS4GkMW0wTdCeWj25PkUJ92FaM3hkQCjhZmIF8qkVEzW+fU2RXLyHhJxQqutG4hDKMq5Gxs+bIZ889/ksXfMm/RTbVdBAQlr2M4FUajbg0dtlYh2LA4Bo8Rs7jQoOOmekBR1NoX858EBRWbdlEPUy9pbkZaCdNeaI7aATJ6zzul26UmHaEc+DWBxhhuZFV0JaH8bK46t/1AltVs7YPORJJhj+adB7IxFQo34BzbjfvubL0U7AKBWZXeIxToDtbUIa4D3uIZ7jSMwJECOyi+dCoTVyLs9GkfwCF1F8NqK9GouNpqgwgid7xsqWRo5lNIAWkl6aUAw2taW+scYop25
    redis-password: AgBdr2fp5ya0IE3+LI6mQCUdFFk2FvTGcYJ8IlsjHpimKMjNCnPQIoJNgiUnO9raUXkaBExzQ9FNtG54UFXZkAvPtBaMZeMyZMPJt31MALBGkL77JqzFu2CKj85uGeVbfXzPKKELsbX8Qu+VovQ50roUI9c2rS78iU/aqCn36uZ6xF3Ovg+3tB+vSjcJ/Jo7+z/UAK1ngZz8rI7GW5UkTSUNAlZ643zGU7odHNHUseJ9dEdck3wg4x0C3MGFl9rFHPyTUWBgZCqncAgIV6PeC0UP6ia3hxpbeltGH1e5d8BnoOEpc9YDt78XV8OrSZ4Z4RJykziKh1hUf6p5Y81Su/7baInrXWlt9iZmH47yCdG7AEwBaTDdIxaf+AM+dU/4pxRynz8NjIP4ZzupCVgkgc+mO5t7Ok6URtHOKORGGHR0VEJ4Da7PPHW5V6ctPvnCNdPdbNYDkjDcqySbT3mBGfov4GC5CDSBf0RuEdhz0qiY6ekFjIFrdtdnF6jz3acQUdMXjD/09r4gwZ8S/K77/JVqPDLR+qxCcWZpxBZNoUCnJj5Zxu4KqHxoZ1OR4XXHbpal6sAobtdP3BcQOI9EpAnGaaY43KtbJp1aOHsONiPkxSuEtrf9qGp8sH1OC7nia9sKrX9Y8HNElCBv5aX5L+xkvCEIwqwKHxEdp0/O1qRmfSoHLMNoEMLyX1OtgI7V5xWoxN35FbDLxiol+uyOvxaxVEqGex/QTz5Tnww9kCSmfOx+hadCmasFGt9pKftUgFB3yGhzT/0t56foJjvdEhp5
  template:
    metadata:
      name: n8n-valkey-credentials
      namespace: n8n
    type: Opaque
